backend:
  name: github
  repo: cjonesie/hugo-resturaunt-tutorial

media_folder: "src/img/gallery" # Folder where user uploaded files should go

collections: # A list of collections the CMS should be able to edit
  - name: food # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Food Item" # Used in the UI, ie.: "New Post"
    folder: "_site/content/food" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Name of Item", name: "title", widget: "string"}
      - {label: "Supported Meals", name: "categories", widget: "list", default: ["lunch",
      "dinner"]}
      - {label: "Ingredients", name: "type", widget: "string", default: "cadelyyy"}
      - {label: "Price", name: "price", widget: "string"}